# Generated by Django 5.1.1 on 2024-09-26 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='center_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.center'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.user'),
        ),
        migrations.AlterField(
            model_name='classified',
            name='center_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.center'),
        ),
        migrations.AlterField(
            model_name='limit',
            name='center_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.center'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='center_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.center'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='center_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.center'),
        ),
        migrations.AlterField(
            model_name='throw',
            name='center_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.center'),
        ),
        migrations.AlterField(
            model_name='throw',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='winner',
            name='center_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.center'),
        ),
        migrations.AlterField(
            model_name='winner',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.user'),
        ),
    ]
