# Generated by Django 5.1.1 on 2024-09-18 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bets',
            new_name='Bet',
        ),
        migrations.RenameModel(
            old_name='Clasifieds',
            new_name='Clasified',
        ),
        migrations.RenameModel(
            old_name='Limits',
            new_name='Limit',
        ),
        migrations.RenameModel(
            old_name='Plans',
            new_name='Plan',
        ),
        migrations.RenameModel(
            old_name='Chedule',
            new_name='Schedule',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.RenameModel(
            old_name='Winners',
            new_name='Winner',
        ),
    ]
